name = "tokentracker"
workers_dev = true
compatibility_date = "2023-07-01"
send_metrics = false
main = "server/index.ts"
tsconfig = "tsconfig.json"

[durable_objects]
bindings = [
  { name = "client_logs", class_name = "ClientLog" }
]

[[migrations]]
tag = "v1"
new_classes = ["ClientLog"]

[placement]
mode = "smart"
