name = "tokentracker"
workers_dev = true
compatibility_date = "2023-07-01"
send_metrics = false
main = "server/index.ts"
tsconfig = "tsconfig.json"
# tracks changes on branch `prod`
route = "backend.tokentracker.xyz"

durable_objects.bindings = [
  { name = "client_logs", class_name = "ClientLog"}
]

[[migrations]]
tag = "v1"
new_classes = ["ClientLog"]

[placement]
mode = "smart"

[env.stage]
# tracks changes on branch `main`
route = "staging.backend.tokentracker.xyz"

durable_objects.bindings = [
  { name = "client_logs", class_name = "ClientLog"}
]

[env.dev]
# tracks latest changes in PRs
route = "dev.backend.tokentracker.xyz"

durable_objects.bindings = [
  { name = "client_logs", class_name = "ClientLog"}
]
