name = "tokentracker"
workers_dev = true
compatibility_date = "2023-07-01"
send_metrics = false
main = "server/index.ts"
tsconfig = "tsconfig.json"
# tracks changes on branch `main`
route = { pattern = "backend.mytokentracker.xyz", custom_domain = true }

durable_objects.bindings = [
  { name = "client_logs", class_name = "ClientLog"}
]

[[migrations]]
tag = "v1"
new_classes = ["ClientLog"]

[placement]
mode = "smart"

[env.staging]
# tracks changes on branch `staging`
route = { pattern = "staging-backend.mytokentracker.xyz", custom_domain = true }

durable_objects.bindings = [
  { name = "client_logs", class_name = "ClientLog"}
]

[env.dev]
# tracks latest changes in PRs
route = { pattern = "dev-backend.mytokentracker.xyz", custom_domain = true }

durable_objects.bindings = [
  { name = "client_logs", class_name = "ClientLog"}
]
